export const READ_TICKET_STATUS = "READ_TICKET_STATUS";
export const READ_TICKET_STATUS_REJECT = "READ_TICKET_STATUS_REJECT";
export const READ_TICKET_STATUS_FULFILLED = "READ_TICKET_STATUS_FULFILLED";
