export const READ_EMAIL_NOTIF = "READ_EMAIL_NOTIF";
export const READ_EMAIL_NOTIF_REJECT = "READ_EMAIL_NOTIF_REJECT";
export const READ_EMAIL_NOTIF_FULFILLED = "READ_EMAIL_NOTIF_FULFILLED";

export const READ_DETAIL_EMAIL_NOTIF = "READ_DETAIL_EMAIL_NOTIF";
export const READ_DETAIL_EMAIL_NOTIF_REJECT = "READ_DETAIL_EMAIL_NOTIF_REJECT";
export const READ_DETAIL_EMAIL_NOTIF_FULFILLED =
  "READ_DETAIL_EMAIL_NOTIF_FULFILLED";

export const CREATE_EMAIL_NOTIF = "CREATE_EMAIL_NOTIF";
export const CREATE_EMAIL_NOTIF_REJECT = "CREATE_EMAIL_NOTIF_REJECT";
export const CREATE_EMAIL_NOTIF_FULFILLED = "CREATE_EMAIL_NOTIF_FULFILLED";

export const UPDATE_EMAIL_NOTIF = "UPDATE_EMAIL_NOTIF";
export const UPDATE_EMAIL_NOTIF_REJECT = "UPDATE_EMAIL_NOTIF_REJECT";
export const UPDATE_EMAIL_NOTIF_FULFILLED = "UPDATE_EMAIL_NOTIF_FULFILLED";

export const DELETE_EMAIL_NOTIF = "DELETE_EMAIL_NOTIF";
export const DELETE_EMAIL_NOTIF_REJECT = "DELETE_EMAIL_NOTIF_REJECT";
export const DELETE_EMAIL_NOTIF_FULFILLED = "DELETE_EMAIL_NOTIF_FULFILLED";
