export const READ_CATEGORY = "READ_CATEGORY";
export const READ_CATEGORY_REJECT = "READ_CATEGORY_REJECT";
export const READ_CATEGORY_FULFILLED = "READ_CATEGORY_FULFILLED";

export const READ_DETAIL_CATEGORY = "READ_DETAIL_CATEGORY";
export const READ_DETAIL_CATEGORY_REJECT = "READ_DETAIL_CATEGORY_REJECT";
export const READ_DETAIL_CATEGORY_FULFILLED = "READ_DETAIL_CATEGORY_FULFILLED";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_REJECT = "CREATE_CATEGORY_REJECT";
export const CREATE_CATEGORY_FULFILLED = "CREATE_CATEGORY_FULFILLED";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_REJECT = "UPDATE_CATEGORY_REJECT";
export const UPDATE_CATEGORY_FULFILLED = "UPDATE_CATEGORY_FULFILLED";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_REJECT = "DELETE_CATEGORY_REJECT";
export const DELETE_CATEGORY_FULFILLED = "DELETE_CATEGORY_FULFILLED";
