export const READ_REPORT = "READ_REPORT";
export const READ_REPORT_REJECT = "READ_REPORT_REJECT";
export const READ_REPORT_FULFILLED = "READ_REPORT_FULFILLED";

export const READ_COUNT_REPORT_BY_STATUS = "READ_COUNT_REPORT_BY_STATUS";
export const READ_COUNT_REPORT_BY_STATUS_REJECT =
  "READ_COUNT_REPORT_BY_STATUS_REJECT";
export const READ_COUNT_REPORT_BY_STATUS_FULFILLED =
  "READ_COUNT_REPORT_BY_STATUS_FULFILLED";
