export const READ_REPORT = "READ_REPORT";
export const READ_REPORT_REJECT = "READ_REPORT_REJECT";
export const READ_REPORT_FULFILLED = "READ_REPORT_FULFILLED";

export const READ_COUNT_REPORT_ACTIVITY = "READ_COUNT_REPORT_ACTIVITY";
export const READ_COUNT_REPORT_ACTIVITY_REJECT =
  "READ_COUNT_REPORT_ACTIVITY_REJECT";
export const READ_COUNT_REPORT_ACTIVITY_FULFILLED =
  "READ_COUNT_REPORT_ACTIVITY_FULFILLED";
