export const READ_TICKET = "READ_TICKET";
export const READ_TICKET_REJECT = "READ_TICKET_REJECT";
export const READ_TICKET_FULFILLED = "READ_TICKET_FULFILLED";

export const CREATE_TICKET = "CREATE_TICKET";
export const CREATE_TICKET_REJECT = "CREATE_TICKET_REJECT";
export const CREATE_TICKET_FULFILLED = "CREATE_TICKET_FULFILLED";

export const READ_DETAIL_TICKET = "READ_DETAIL_TICKET";
export const READ_DETAIL_TICKET_REJECT = "READ_DETAIL_TICKET_REJECT";
export const READ_DETAIL_TICKET_FULFILLED = "READ_DETAIL_TICKET_FULFILLED";

export const UPDATE_TICKET = "UPDATE_TICKET";
export const UPDATE_TICKET_REJECT = "UPDATE_TICKET_REJECT";
export const UPDATE_TICKET_FULFILLED = "UPDATE_TICKET_FULFILLED";

export const REPLY_TICKET = "REPLY_TICKET";
export const REPLY_TICKET_REJECT = "REPLY_TICKET_REJECT";
export const REPLY_TICKET_FULFILLED = "REPLY_TICKET_FULFILLED";

export const START_TICKET = "START_TICKET";
export const START_TICKET_REJECT = "START_TICKET_REJECT";
export const START_TICKET_FULFILLED = "START_TICKET_FULFILLED";

export const CLOSE_TICKET = "CLOSE_TICKET";
export const CLOSE_TICKET_REJECT = "CLOSE_TICKET_REJECT";
export const CLOSE_TICKET_FULFILLED = "CLOSE_TICKET_FULFILLED";
