export const READ_TICKET = "READ_TICKET";
export const READ_TICKET_REJECT = "READ_TICKET_REJECT";
export const READ_TICKET_FULFILLED = "READ_TICKET_FULFILLED";

export const CREATE_TICKET = "CREATE_TICKET";
export const CREATE_TICKET_REJECT = "CREATE_TICKET_REJECT";
export const CREATE_TICKET_FULFILLED = "CREATE_TICKET_FULFILLED";

export const READ_DETAIL_TICKET = "READ_DETAIL_TICKET";
export const READ_DETAIL_TICKET_REJECT = "READ_DETAIL_TICKET_REJECT";
export const READ_DETAIL_TICKET_FULFILLED = "READ_DETAIL_TICKET_FULFILLED";