export const READ_ROLE = "READ_ROLE";
export const READ_ROLE_REJECT = "READ_ROLE_REJECT";
export const READ_ROLE_FULFILLED = "READ_ROLE_FULFILLED";

export const READ_DETAIL_ROLE = "READ_DETAIL_ROLE";
export const READ_DETAIL_ROLE_REJECT = "READ_DETAIL_ROLE_REJECT";
export const READ_DETAIL_ROLE_FULFILLED = "READ_DETAIL_ROLE_FULFILLED";

export const CREATE_ROLE = "CREATE_ROLE";
export const CREATE_ROLE_REJECT = "CREATE_ROLE_REJECT";
export const CREATE_ROLE_FULFILLED = "CREATE_ROLE_FULFILLED";

export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ROLE_REJECT = "UPDATE_ROLE_REJECT";
export const UPDATE_ROLE_FULFILLED = "UPDATE_ROLE_FULFILLED";

export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_REJECT = "DELETE_ROLE_REJECT";
export const DELETE_ROLE_FULFILLED = "DELETE_ROLE_FULFILLED";
