export const READ_USER = "READ_USER";
export const READ_USER_REJECT = "READ_USER_REJECT";
export const READ_USER_FULFILLED = "READ_USER_FULFILLED";

export const READ_USER_DETAIL = "READ_USER_DETAIL";
export const READ_USER_DETAIL_REJECT = "READ_USER_DETAIL_REJECT";
export const READ_USER_DETAIL_FULFILLED = "READ_USER_DETAIL_FULFILLED";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_REJECT = "CREATE_USER_REJECT";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_REJECT = "UPDATE_USER_REJECT";
export const UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_REJECT = "UPDATE_USER_PROFILE_REJECT";
export const UPDATE_USER_PROFILE_FULFILLED = "UPDATE_USER_PROFILE_FULFILLED";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_REJECT = "DELETE_USER_REJECT";
export const DELETE_USER_FULFILLED = "DELETE_USER_FULFILLED";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_REJECT = "RESET_PASSWORD_REJECT";
export const RESET_PASSWORD_FULFILLED = "RESET_PASSWORD_FULFILLED";
